name: fruitgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - pip=22.3.1
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - open-clip-torch
  - plyfile=0.8.1
  - tqdm
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - numpy
  - imageio
  - configargparse
  - open3d=0.17.0
  - typing
  - pathlib
  - pip:
      - submodules/segment-anything-langsplat
      - submodules/langsplat-rasterization
      - submodules/simple-knn
